// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKSmBWYX8T4bzOxbeWxIQ6dKrJlCJzrpY',
    appId: '1:352294110923:web:dd19ebc2709880e362fd4e',
    messagingSenderId: '352294110923',
    projectId: 'desucces-ec2d3',
    authDomain: 'desucces-ec2d3.firebaseapp.com',
    storageBucket: 'desucces-ec2d3.appspot.com',
    measurementId: 'G-PQJ1N8XMKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ZdhgqYyillriiBA8bzOPHVRITt269o4',
    appId: '1:352294110923:android:56755befd0011efc62fd4e',
    messagingSenderId: '352294110923',
    projectId: 'desucces-ec2d3',
    storageBucket: 'desucces-ec2d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmaBK3ew_Y6v-4M2mLT5QCtnCtd34g5GA',
    appId: '1:352294110923:ios:569d3d94826dd67b62fd4e',
    messagingSenderId: '352294110923',
    projectId: 'desucces-ec2d3',
    storageBucket: 'desucces-ec2d3.appspot.com',
    androidClientId: '352294110923-v5baj97skff2mvldjfajvs6mdmfkoarl.apps.googleusercontent.com',
    iosClientId: '352294110923-dh08imiuro62vi11bd45nsol7sip5u60.apps.googleusercontent.com',
    iosBundleId: 'com.dcsucces.dcsucces',
  );
}
